name             'eucatelemetry'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures eucatelemetry'
long_description 'Installs/Configures eucatelemetry'
version          '0.1.0'
depends          'grafana'
depends          'influxdb'
depends          'supervisor'
depends          'collectd'